In [15]:
import numpy as np 
import pickle
reference_100 = np.array( [0.785, 0.891,0.652,0.885] )
def mat_from_pkl(a):
    with open(a, "rb") as input_file:
        data = pickle.load(input_file)
    res= np.unique( np.array( data[-1] ), return_index =True) 
    idx = res[1]
    mat = np.zeros( (idx.shape[0], idx.shape[0]))
    data = [np.array(d) for d in data]

    el = data[-1].max()+1
    for i in range( el ):
        for j in range( el  ):
            mat[i,j] = data[j][data[-1] == i][-1]
    return mat

def get(a, start=0):
    with open(a, "rb") as input_file:
            data = pickle.load(input_file)
    res= np.unique( np.array( data[-1] ), return_index =True) 
    idx = res[1]
    mat = np.zeros( (idx.shape[0], idx.shape[0]))
    data = [np.array(d) for d in data]

    el = data[-1].max()+1
    for i in range( el ):
        for j in range( el  ):
            mat[i,j] = data[j][data[-1] == i][-1]

    ta = mat
    mat = mat[start:,start:]
    print(mat)
    
    elements = np.ones_like(mat)

    ACC = np.tril(mat, k =0).sum()  / np.tril(elements, k =0).sum() 
    print ( "ACC: ", round( ACC*100,1) )
    FWT = np.triu(mat, k =1).sum()  / np.triu(elements, k =1).sum() 
    print ( "FWT: ", round( FWT*100,1))
    dia = np.diagonal(mat)
    mat_out = np.copy(mat)
    for i in range(mat.shape[1]):
        mat_out[:,i] -= dia[i]
    BWT = np.tril(mat_out, k =-1).sum() / np.tril(elements, k =-1).sum() 
    print ( "BWT: ", round( BWT* 100,1) )   
    print( "Omega",  np.mean( mat[-1,:]/reference_100 ) )
    print( round( ACC*100,1), " & ", round( FWT*100,1) ,"&",round( BWT* 100,1) ,"&",round(np.mean( mat[-1,:]/reference_100 )* 100,1) )
    return ta

In [22]:
b = "/home/jonfrey/Results/semi_4_scenes/2021-07-28T21:02:55_cl_005_unltimited_mem_ratio05/val_res.pkl"
mat = get(b,start=1)
mat[0,1:].mean(), mat[-1,1:].mean(), mat[1:,1:][np.eye(4)==1].mean()

mat[-1,1:].mean()-mat[0,1:].mean()

[[0.66129577 0.5288769  0.37558588 0.61942613]
 [0.65451401 0.51616317 0.34464055 0.65427893]
 [0.64370358 0.46484619 0.39307958 0.62020737]
 [0.66138887 0.46335819 0.39251283 0.74929219]]
ACC:  56.0
FWT:  52.4
BWT:  -2.1
Omega 0.7028119627209155
56.0  &  52.4 & -2.1 & 70.3


0.007923625409603119

In [23]:
a = "/home/jonfrey/Results/scannet_cl_buffer_filling/2021-07-19T10:36:55_random/val_res.pkl"
get(a,start=1)
a = "/home/jonfrey/Results/scannet_teacher/2021-07-19T11:14:42_hard1/val_res.pkl"
get(a,start=1)
a = "/home/jonfrey/Results/scannet_teacher/2021-07-19T11:14:42_soft10/val_res.pkl"
get(a,start=1)

[[0.81615472 0.53594357 0.33744022 0.64060748]
 [0.80342025 0.88968062 0.34354961 0.59634465]
 [0.7593562  0.88378012 0.64375269 0.53437626]
 [0.78763568 0.8945756  0.57710427 0.86928439]]
ACC:  79.2
FWT:  49.8
BWT:  -2.8
Omega 0.9686855182558156
79.2  &  49.8 & -2.8 & 96.9
[[0.80719364 0.58249032 0.37278444 0.65457797]
 [0.79437721 0.88636494 0.35975188 0.65840602]
 [0.77939534 0.80844223 0.61455297 0.62829745]
 [0.77937579 0.86153513 0.61288512 0.89036882]]
ACC:  78.3
FWT:  54.3
BWT:  -2.9
Omega 0.9764600694927172
78.3  &  54.3 & -2.9 & 97.6
[[0.81926394 0.53537816 0.32664412 0.64932454]
 [0.79683191 0.89618993 0.32402092 0.64283365]
 [0.73547    0.78074902 0.64954871 0.55053771]
 [0.73220366 0.81339157 0.62468535 0.90118635]]
ACC:  77.5
FWT:  50.5
BWT:  -6.9
Omega 0.9555092294863179
77.5  &  50.5 & -6.9 & 95.6
